### ISSUE TITLE
[Feature request] Transaction channel

### ISSUE THREAD

**Issue by Oxygenism** [Piggy-Loyalty/piggy-php-sdk#24]
Would it be possible to add the 'channel' column, in the Piggy transaction dashboard, to be available within the transaction response? I haven't quite checked if you can deduce this value from the 'shop id' value, but that is rather cumbersome, if it is the case. 

Having it be filterable on the request would be nice, too. But having it as a response attribute would resolve my needs fairly well. 

![image](https://github.com/Piggy-Loyalty/piggy-php-sdk/assets/19476449/4d6a7285-4ba8-44d4-b96a-78940acd6272)

Thank you :)

**Comment by iDiegoNL** [comment]
Hi Oxygenism! Thanks for your feature request.

We are discussing it internally what the best solution for this would be to add this to our API / SDK, I will let you know once we have any updates regarding this!

**Comment by iDiegoNL** [comment]
Thanks for your patience! The channel for loyalty transactions has been added to our API, and in the SDK starting from [v3.5.0](https://github.com/Piggy-Loyalty/piggy-php-sdk/releases/tag/3.5.0).

**Comment by Oxygenism** [comment]
Thank you ^^ it works great!
