### ISSUE TITLE
GiftcardTransaction

### ISSUE THREAD

**Issue by MV-ICT** [Piggy-Loyalty/piggy-php-sdk#6]
Hallo,

Ik probeer een GiftcardTransaction toe te voegen maar krijg bij alle kaarten de volgende foutmelding:
"{"code":1114,"status_code":400,"message":"The giftcard is upgradeable"}"
Bij kaarten welke opwaardeerbaar zijn en bij kaarten welke niet opwaardeerbaar zijn. Ook bij een negatief bedrag.

**Comment by EdingerMike** [comment]
Hi @MV-ICT,

It is indeed not possible to create a giftcard transation for upgradable giftcards.

> Only giftcards that are not re-incrementable can be used for the creation of giftcard transactions through OAuth. This is due to security reasons.

[https://docs.piggy.eu/oauth/giftcards/transactions](https://docs.piggy.eu/oauth/giftcards/transactions)

This error will only be returned when the given giftcard is upgradable. Please make sure you use a giftcard that is not upgradeable.

**Comment by EdingerMike** [comment]
I will mark this as closed for now, let us know if you are still experiencing any issues.
